config/routes.rb
Rails.application.routes.draw do
  root :to => 'products#landing'

  resources :products do
    resources :reviews
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :reviews
  validates :name, :presence => true
  validates :cost, :presence => true
  validates :origin, :presence => true
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :product

  validates :author, :presence => true
  validates :content_body, :presence => true
  validates :rating, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      flash[:notice] = "Product successfully added!"
      redirect_to products_path
    else
      render :new
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    if @product.update(product_params)
      redirect_to products_path
    else
      render :edit
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to products_path
  end
private
  def product_params
    params.require(:product).permit(:name, :cost, :origin)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @product = Product.find(params[:product_id])
    @review = @product.reviews.new
  end

  def create
    @product = Product.find(params[:product_id])
    @review = @product.reviews.new(review_params)
    if @review.save
      redirect_to product_path(@review.product)
    else
      render :new
    end
  end

  def edit
    @product = Product.find(params[:product_id])
    @review = Review.find(params[:id])
    render :edit
  end

  def update
    @product = Product.find(params[:product_id])
    @review = Review.find(params[:id])
    if @review.update(review_params)
      redirect_to product_path(@review.product)
    else
      render :edit
    end
  end

  def destroy
    @product = Product.find(params[:product_id])
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to product_path(@review.product)
  end
private
  def review_params
    params.require(:review).permit(:author, :content_body, :rating, :product_id)

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/_form.html.erb
<%= render "layouts/errors", :object => @product %>

<%= form_for @product do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :cost %>
  <%= f.number_field :cost %>
  <%= f.label :origin %>
  <%= f.text_field :origin %>
  <%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MarioFoodSite</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/products/edit.html.erb
<h1>Edit product</h1>

<%= render('layouts/errors', :object => @product) %>

<%= form_for @product do |f| %>
  <%= f.label :description %>
  <%= f.text_field :description %>
  <%= f.label :done %>
  <%= f.check_box :done %>
  <p><%= f.submit %></p>
<% end %>

app/views/products/index.html.erb
<h1>Products</h1>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
<ul>
  <h4>products:</h4>
  <% @products.each do |product| %>

    <li><%= link_to product.name, product_path(product) %>|<%= product.cost%>|<%=product.origin%></li>

  <% end %>

</ul>

<hr>

<%= link_to "New product",  new_product_path %>

app/views/products/landing.html.erb
<h6>Landing Page</h6>

<h1>Mario's Food Product Rating Site!</h1>

<h3>Welcome!</h3>
<h3>About us:</h3>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>

<ul>
<p>Most Recently Added Food Products:</p>
</ul>

<ul>
<p>Most Reviewed Food Products:</p>
</ul>

<%= link_to "Products",  products_path %>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render "layouts/form" %>

app/views/products/show.html.erb
<% content_for(:name, "Product | Review") %>

<h1><%= @product.name %></h1>

<% if @product.reviews.any? %>
  <h4>Here are the reviews for this product:</h4>
  <ul>

      <h4>Reviews:</h4>
      <% @product.reviews.each do |review| %>
      <li>
      <%= review.author %> | <%=review.content_body%> | <%=review.rating%> | 
      <%= link_to "Edit", edit_product_review_path(@product, review) %> |
      <%= link_to "Delete", product_review_path(@product, review),
                              :data => {:confirm => "Are you sure?",
                                  :method => "delete"} %>
    </li>
      <% end %>
  </ul>

<% else %>
  <p>There are no reviews yet!</p>
<% end %>

<p><%= link_to "Add a review", new_product_review_path(@product) %></p>
<p><%= link_to "Delete Product", product_path(@product),
                         :data => {:confirm => "You sure?",
                                   :method => "delete"} %></p>

<p><%= link_to "Return to products", products_path %></p>

app/views/reviews/_form.html.erb
<%= render('layouts/errors', :object => @review) %>

<%= form_for [@product, @review] do |f| %>
  <%= f.label :author %>
  <%= f.text_field :author %>
  <%= f.label :content_body %>
  <%= f.text_field :content_body %>
  <%= f.label :rating %>
  <%= f.number_field :rating %>

  <p><%= f.submit %></p>
<% end %>

app/views/reviews/edit.html.erb
<h1>Edit Review</h1>

<%= render "form" %>

app/views/reviews/new.html.erb
<h1>New Review for <%= @product.name %></h1>

<%= render 'form' %>